---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/apps/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/packages/sdk"
    schedule:
      interval: "daily"
